name: release

on:
  workflow_dispatch:
jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - uses: rubygems/release-gem@v1
